# Generated by Django 5.2.12 on 2026-04-06 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('insufficient', 'Insufficient'), ('researching', 'Researching'), ('generating_thesis', 'Generating Thesis'), ('generating_pitch', 'Generating Pitch'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('validation_feedback', models.JSONField(blank=True, default=dict)),
                ('tool_plan', models.JSONField(blank=True, default=list)),
                ('tool_results', models.JSONField(blank=True, default=dict)),
                ('thesis_md', models.TextField(blank=True, default='')),
                ('slides_json', models.JSONField(blank=True, default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
